# -*- coding: utf-8 -*-
"""
WindTurbineBlade.py — Autodesk Fusion script.

Builds the rotor assembly from Wind_Turbine_BOM.xlsx as parametric geometry:

    BOM 1100   Blade aeroshell   lofted through ~20 airfoil stations
    BOM 1110   Spar caps         upper and lower, lofted
    BOM 1120   Shear webs        fore and aft, lofted
    BOM 1200   Hub               revolved, with 3 blade flanges at 120 deg
    BOM 1400   Spinner           revolved ogive fairing
    BOM 1500   Root bolting      representative bolt circle

INSTALL AND RUN
---------------
1. Fusion -> Utilities tab -> ADD-INS -> Scripts and Add-Ins (or Shift+S)
2. Scripts -> the green "+" -> "Create New Script" (or point it at this folder)
3. Replace the generated .py with this file, keeping the folder and file names
   the same (Fusion requires MyScript/MyScript.py)
4. Select it -> Run

Everything is driven by CONFIG below. To change the blade, edit CONFIG and re-run.

TWO THINGS WORTH KNOWING BEFORE YOU RUN IT
------------------------------------------
1. FUSION'S INTERNAL UNIT IS THE CENTIMETRE, regardless of what the document
   is displaying. Every dimension in CONFIG is in METRES and is converted once,
   in M2CM. Getting this wrong is the classic Fusion API bug and it produces a
   blade 100x too small rather than an error.

2. "PARAMETRIC" HERE HAS A BOUNDARY. The hub, spinner and bolt circle are built
   from Fusion user parameters, so you can change those in the Parameters dialog
   and the model updates. The blade's lofted profiles CANNOT work that way --
   their spline points are computed by this script and baked into the sketches.
   To change blade chord, twist, thickness or prebend, edit CONFIG and re-run.
   Nothing in the Fusion API makes a swept airfoil loft driven by an equation.

WHAT THIS IS NOT
----------------
The airfoils are generated by the analytic NACA 4-digit formula, scaled to the
thickness distribution in the BOM. They are NOT the DU 00-W-401 / NACA 64-618
sections the BOM actually names -- those are 6-series and DU-series profiles
whose coordinates come from tabulated data, not a closed-form equation, and
inventing numbers for them would be worse than substituting an honest
placeholder. The result has the right planform, twist, thickness distribution
and prebend; the section shapes are representative.

To use the real sections: replace airfoil_section() with a lookup into your own
coordinate tables. That is the only function that needs to change -- everything
downstream consumes normalised (x/c, y/c) point lists.
"""

import math
import traceback

# Fusion modules are imported defensively so the pure-geometry half of this file
# can be imported and unit-tested by an ordinary Python interpreter, outside
# Fusion. See verify_blade_geometry.py.
try:
    import adsk.core
    import adsk.fusion
    _HAS_ADSK = True
except ImportError:
    _HAS_ADSK = False


# =============================================================================
# CONFIG -- every value traces to Wind_Turbine_BOM.xlsx. Metres and degrees.
# =============================================================================

CONFIG = {
    # ---- Rotor, BOM "Design Point" ----------------------------------------
    'n_blades':            3,
    'rotor_radius_m':      60.0,     # 120 m diameter
    'hub_radius_m':        1.5,      # blade starts here
    'precone_deg':         3.0,

    # ---- Blade planform, BOM 1100 -----------------------------------------
    'blade_length_m':      58.5,
    'root_diameter_m':     2.6,      # circular root section
    'max_chord_m':         3.9,      # at max_chord_station
    'max_chord_station':   0.22,     # r/R where chord peaks (BOM: 20-25%)
    'tip_chord_m':         0.6,
    'twist_total_deg':     13.0,     # washout, root to tip
    'prebend_tip_m':       3.0,      # out-of-plane, toward upwind
    'pitch_axis_frac':     0.375,    # chordwise location of the pitch axis

    # ---- Thickness distribution -------------------------------------------
    # t/c falls from a full circle at the root to a thin outboard section.
    # BOM names DU 00-W-401 (40%) inboard and NACA 64-618 (18%) at the tip.
    'tc_root':             1.00,     # circular
    'tc_inboard':          0.40,
    'tc_tip':              0.18,
    'circle_blend_start':  0.03,     # r/R where the circle starts morphing
    'circle_blend_end':    0.22,     # r/R where it is fully an airfoil
    'camber_frac':         0.04,     # NACA 4-digit max camber, m
    'camber_pos':          0.40,     # NACA 4-digit camber position, p

    # ---- Discretisation ----------------------------------------------------
    'n_stations':          8,       # was 20
    'n_airfoil_points':    61,       # per surface; total ~2n
    'loft_stations_only':  True,     # False = also draw every station sketch

    # ---- Internal structure, BOM 1110 / 1120 ------------------------------
    'build_structure':     False,   # was True
    'spar_cap_start_frac': 0.15,     # chordwise extent of the spar caps
    'spar_cap_end_frac':   0.50,
    'spar_cap_thk_m':      0.06,
    'web_thk_m':           0.04,
    'structure_root_frac': 0.05,     # structure runs between these r/R
    'structure_tip_frac':  0.95,

    # ---- Hub, BOM 1200 -----------------------------------------------------
    'build_hub':           False,   # was True
    'hub_envelope_dia_m':  3.4,
    'hub_flange_dia_m':    2.6,
    'hub_flange_len_m':    0.35,

    # ---- Spinner, BOM 1400 -------------------------------------------------
    'build_spinner':       False,   # was True
    'spinner_dia_m':       3.6,
    'spinner_len_m':       2.4,

    # ---- Root bolting, BOM 1500 -------------------------------------------
    'build_root_bolts':    False,   # was True
    'bolt_count':          24,       # representative; BOM says 80-120 per blade
    'bolt_dia_m':          0.036,    # M36
    'bolt_len_m':          0.40,
    'bolt_circle_dia_m':   2.45,
}

M2CM = 100.0   # Fusion's internal unit is the centimetre. See header note 1.


# =============================================================================
# PURE GEOMETRY -- no Fusion dependency, unit-testable outside Fusion
# =============================================================================

def naca4_thickness(x, t):
    """NACA 4-digit half-thickness distribution at chordwise fraction x.

    The -0.1015 final coefficient is the ORIGINAL (open trailing edge) form.
    That is deliberate: it leaves a small blunt trailing edge, which is both
    what thick wind-turbine sections actually have and what lets the profile
    close with a straight TE segment instead of a cusp. A cusped TE lofts
    badly -- Fusion tends to produce a sliver face or fail outright.
    """
    return 5.0 * t * (0.2969 * math.sqrt(x)
                      - 0.1260 * x
                      - 0.3516 * x ** 2
                      + 0.2843 * x ** 3
                      - 0.1015 * x ** 4)


def naca4_camber(x, m, p):
    """Return (camber y, camber slope dy/dx) for the NACA 4-digit mean line."""
    if m <= 0.0 or p <= 0.0:
        return 0.0, 0.0
    if x < p:
        y = (m / p ** 2) * (2.0 * p * x - x ** 2)
        dy = (2.0 * m / p ** 2) * (p - x)
    else:
        y = (m / (1.0 - p) ** 2) * ((1.0 - 2.0 * p) + 2.0 * p * x - x ** 2)
        dy = (2.0 * m / (1.0 - p) ** 2) * (p - x)
    return y, dy


def cosine_spacing(n):
    """Chordwise stations clustered at leading and trailing edge.

    Uniform spacing under-resolves the leading edge, where curvature is
    highest; the loft then shows visible faceting there. Cosine spacing costs
    nothing and fixes it.
    """
    return [0.5 * (1.0 - math.cos(math.pi * i / (n - 1))) for i in range(n)]


def airfoil_section(tc, n_pts, camber_m, camber_p):
    """Normalised airfoil contour for a given thickness-to-chord ratio.

    Returns a list of (x, y) in chord-normalised coordinates, ordered from the
    upper trailing edge, forward over the nose, and back along the lower
    surface to the lower trailing edge. The contour is deliberately left OPEN
    at the trailing edge -- the caller closes it with a straight segment.

    REPLACE THIS FUNCTION to use real tabulated sections (DU 00-W-401,
    NACA 64-618, ...). Nothing downstream depends on how the points are
    produced, only on the ordering and normalisation described above.
    """
    xs = cosine_spacing(n_pts)

    upper, lower = [], []
    for x in xs:
        yt = naca4_thickness(x, tc)
        yc, dyc = naca4_camber(x, camber_m, camber_p)
        theta = math.atan(dyc)
        upper.append((x - yt * math.sin(theta), yc + yt * math.cos(theta)))
        lower.append((x + yt * math.sin(theta), yc - yt * math.cos(theta)))

    # upper TE -> LE, then LE -> lower TE, without repeating the nose point
    return list(reversed(upper)) + lower[1:]


def circle_section(n_pts):
    """Root circle, sampled with the SAME parameterisation as the airfoil.

    Matching the point ordering and count is what makes the blend in
    blended_section() a simple element-wise interpolation. A circle sampled by
    equal angle instead would pair the wrong points together and the morph
    would twist through the transition region.
    """
    xs = cosine_spacing(n_pts)
    r = 0.5

    def y_of(x):
        d = r ** 2 - (x - 0.5) ** 2
        return math.sqrt(d) if d > 0.0 else 0.0

    upper = [(x, y_of(x)) for x in xs]
    lower = [(x, -y_of(x)) for x in xs]
    return list(reversed(upper)) + lower[1:]


def smoothstep(a, b, x):
    """Hermite blend, 0 below a and 1 above b, with zero slope at both ends.

    Zero slope matters here: a linear blend produces a visible crease in the
    lofted surface where the transition starts and stops.
    """
    if b <= a:
        return 0.0 if x < a else 1.0
    t = min(1.0, max(0.0, (x - a) / (b - a)))
    return t * t * (3.0 - 2.0 * t)


def chord_at(rR, cfg):
    """Chord [m] at span fraction rR, in three pieces.

    Root -> max chord is a smooth rise; max chord -> tip is a near-linear
    taper. Real blades are defined by a table, not a formula; this reproduces
    the three planform numbers the BOM actually gives (root diameter, max
    chord and station, tip chord) and interpolates smoothly between them.
    """
    root_c = cfg['root_diameter_m']
    peak_c = cfg['max_chord_m']
    tip_c = cfg['tip_chord_m']
    peak_r = cfg['max_chord_station']

    if rR <= peak_r:
        return root_c + (peak_c - root_c) * smoothstep(0.0, peak_r, rR)

    # Linear outboard taper. An earlier version used t**0.85 here, which is
    # wrong in a way that is easy to miss: d/dt of t^0.85 is 0.85*t^-0.15,
    # which is INFINITE at t = 0. The chord therefore arrived at max chord
    # with zero slope and left it with infinite slope -- a derivative
    # singularity right at the shoulder, which pinches the loft. Any exponent
    # < 1 has this problem. Linear keeps the slope finite, and a near-linear
    # outboard taper is how blade planforms are normally tabulated anyway.
    #
    # There is still a finite slope DISCONTINUITY at peak_r. That is a real
    # planform feature -- blades do have a distinct max-chord shoulder -- not
    # a numerical artefact.
    t = (rR - peak_r) / (1.0 - peak_r)
    return peak_c + (tip_c - peak_c) * t


def twist_at(rR, cfg):
    """Twist [deg], washout from root to tip.

    Maximum inboard where the local inflow angle is steepest, decaying to
    ~0 at the tip. The exponent shapes how fast it unwinds.
    """
    return cfg['twist_total_deg'] * (1.0 - rR) ** 1.6


def thickness_at(rR, cfg):
    """Thickness-to-chord ratio, from a circular root to a thin tip."""
    blend = smoothstep(cfg['circle_blend_start'], cfg['circle_blend_end'], rR)
    inboard = cfg['tc_root'] + (cfg['tc_inboard'] - cfg['tc_root']) * blend
    if rR <= cfg['circle_blend_end']:
        return inboard
    t = (rR - cfg['circle_blend_end']) / (1.0 - cfg['circle_blend_end'])
    return cfg['tc_inboard'] + (cfg['tc_tip'] - cfg['tc_inboard']) * t


def prebend_at(rR, cfg):
    """Out-of-plane prebend [m].

    Cubic in span so both displacement and slope are zero at the root, which
    is what a cantilever pre-deflection actually looks like. The BOM gives the
    tip value; the shape is the standard assumption.
    """
    return cfg['prebend_tip_m'] * (rR ** 3)


def blended_section(rR, cfg):
    """Normalised contour at span fraction rR: circle, airfoil, or a morph."""
    n = cfg['n_airfoil_points']
    tc = thickness_at(rR, cfg)
    w = smoothstep(cfg['circle_blend_start'], cfg['circle_blend_end'], rR)

    if w <= 0.0:
        return circle_section(n)
    if w >= 1.0:
        return airfoil_section(tc, n, cfg['camber_frac'], cfg['camber_pos'])

    circ = circle_section(n)
    foil = airfoil_section(tc, n, cfg['camber_frac'], cfg['camber_pos'])
    return [(c[0] + (f[0] - c[0]) * w, c[1] + (f[1] - c[1]) * w)
            for c, f in zip(circ, foil)]


def apply_twist_prebend(pts_local_m, rR, cfg):
    """Rotate about the pitch axis by the local twist, then offset by prebend.

    Split out from the section builders so that the aeroshell and the internal
    structure provably share ONE transform. When each built its own, a change
    to the twist convention could silently move the skin and not the spar --
    which is exactly the class of error the containment test now catches.
    """
    tw = math.radians(twist_at(rR, cfg))
    yb = prebend_at(rR, cfg)
    ct, st = math.cos(tw), math.sin(tw)
    return [(x * ct - y * st, x * st + y * ct + yb) for (x, y) in pts_local_m]


def station_points_local(rR, cfg):
    """Blade contour at rR in the UNTWISTED section frame, METRES.

    Origin is the pitch axis, X chordwise, Y out-of-plane.
    """
    c = chord_at(rR, cfg)
    ax = cfg['pitch_axis_frac']
    return [((xn - ax) * c, yn * c) for (xn, yn) in blended_section(rR, cfg)]


def station_points(rR, cfg):
    """Blade contour at span fraction rR, in blade coordinates, METRES.

    Frame: X = chordwise, Y = out-of-plane (rotor axis), Z = spanwise.
    Order is scale -> shift to pitch axis -> twist -> prebend, and it matters:
    a real blade twists about its pitch axis, so the pitch-axis shift has to
    happen before the rotation, not after.
    """
    return apply_twist_prebend(station_points_local(rR, cfg), rR, cfg)


def surface_y_at(rR, cfg, x_frac):
    """Upper and lower surface y at a chordwise fraction, chord-normalised.

    Interpolates the ACTUAL section contour rather than assuming the surfaces
    sit at +/- half the maximum thickness about y = 0. That assumption is only
    true for a symmetric section; these are cambered, so the real surfaces are
    at (yc + yt) and (yc - yt), both shifted upward by the camber. Placing
    internal structure on the chord line instead of the camber line pushes the
    lower spar cap straight through the skin.
    """
    pts = blended_section(rR, cfg)
    m = (len(pts) + 1) // 2
    upper = [pts[m - 1 - k] for k in range(m)]     # LE -> TE
    lower = [pts[m - 1 + k] for k in range(m)]     # LE -> TE

    def interp(seq):
        for i in range(len(seq) - 1):
            x0, y0 = seq[i]
            x1, y1 = seq[i + 1]
            if (x0 - 1e-12) <= x_frac <= (x1 + 1e-12) and abs(x1 - x0) > 1e-12:
                f = (x_frac - x0) / (x1 - x0)
                return y0 + f * (y1 - y0)
        return seq[-1][1] if x_frac > seq[-1][0] else seq[0][1]

    return interp(upper), interp(lower)


def span_stations(cfg):
    """Span fractions for the loft sections.

    Clustered toward the root, where chord and thickness change fastest --
    uniform spacing there produces a visibly lumpy transition region.
    """
    n = cfg['n_stations']
    return [(i / (n - 1.0)) ** 1.25 for i in range(n)]


SKIN_CLEARANCE = 0.97   # fraction of the local half-depth the structure may use


def spar_cap_rect_local(rR, cfg, upper):
    """Spar-cap section at rR in the UNTWISTED frame, metres.

    A rectangle riding just inside the upper or lower skin, spanning the
    chordwise extent in CONFIG. The real cap follows the surface curvature; a
    rectangle of equivalent area is the standard first-order idealisation and
    is what a beam model of the blade assumes anyway.

    The inner surface is found from the ACTUAL contour at both chordwise ends
    (see surface_y_at) and the more restrictive of the two is used, so the cap
    stays inside the skin even where the section is strongly cambered.
    """
    c = chord_at(rR, cfg)
    ax = cfg['pitch_axis_frac']
    thk = cfg['spar_cap_thk_m']
    f0, f1 = cfg['spar_cap_start_frac'], cfg['spar_cap_end_frac']

    x0 = (f0 - ax) * c
    x1 = (f1 - ax) * c

    up0, lo0 = surface_y_at(rR, cfg, f0)
    up1, lo1 = surface_y_at(rR, cfg, f1)

    if upper:
        y_skin = min(up0, up1) * c * SKIN_CLEARANCE
        yo, yi = y_skin, y_skin - thk
    else:
        y_skin = max(lo0, lo1) * c * SKIN_CLEARANCE
        yo, yi = y_skin, y_skin + thk

    return [(x0, yo), (x1, yo), (x1, yi), (x0, yi)]


def shear_web_rect_local(rR, cfg, fore):
    """Shear web section at rR in the UNTWISTED frame, metres.

    Spans between the actual upper and lower surfaces at its chordwise
    station, again from the real contour rather than from +/- half thickness.
    """
    c = chord_at(rR, cfg)
    ax = cfg['pitch_axis_frac']
    thk = cfg['web_thk_m']

    frac = cfg['spar_cap_start_frac'] if fore else cfg['spar_cap_end_frac']
    xc = (frac - ax) * c
    x0, x1 = xc - 0.5 * thk, xc + 0.5 * thk

    # Sample the surface at BOTH edges of the web, not just its centreline,
    # and take the more restrictive value. Outboard the chord falls to ~1 m
    # while the web keeps its fixed 40 mm width, so the surface curves
    # appreciably across the web -- sampling only the centreline let the
    # corners protrude through the skin near the tip. The fore web sits close
    # to the leading edge, where curvature is highest, so it fails first.
    half_frac = 0.5 * thk / max(c, 1e-6)
    f0 = min(max(frac - half_frac, 0.0), 1.0)
    f1 = min(max(frac + half_frac, 0.0), 1.0)

    up0, lo0 = surface_y_at(rR, cfg, f0)
    up1, lo1 = surface_y_at(rR, cfg, f1)

    y_hi = min(up0, up1) * c * SKIN_CLEARANCE
    y_lo = max(lo0, lo1) * c * SKIN_CLEARANCE

    return [(x0, y_lo), (x1, y_lo), (x1, y_hi), (x0, y_hi)]


def spar_cap_rect(rR, cfg, upper):
    """Spar-cap section in blade coordinates, metres."""
    return apply_twist_prebend(spar_cap_rect_local(rR, cfg, upper), rR, cfg)


def shear_web_rect(rR, cfg, fore):
    """Shear web section in blade coordinates, metres."""
    return apply_twist_prebend(shear_web_rect_local(rR, cfg, fore), rR, cfg)


def blade_z_m(rR, cfg):
    """Spanwise position [m] from the rotor centre."""
    return cfg['hub_radius_m'] + rR * cfg['blade_length_m']


# =============================================================================
# FUSION BUILDERS
# =============================================================================

def _pt(x_m, y_m):
    """Point3D in a sketch, converting metres -> Fusion's centimetres."""
    return adsk.core.Point3D.create(x_m * M2CM, y_m * M2CM, 0.0)


def _offset_plane(comp, z_m):
    planes = comp.constructionPlanes
    pin = planes.createInput()
    pin.setByOffset(comp.xYConstructionPlane,
                    adsk.core.ValueInput.createByReal(z_m * M2CM))
    return planes.add(pin)


def _closed_profile_sketch(comp, z_m, pts_m, name):
    """Sketch a closed contour: fitted spline plus a straight closing segment.

    Returns the resulting Profile, or None if Fusion did not form one -- which
    happens if the contour self-intersects. Returning None rather than raising
    lets the caller skip one bad station and still loft the rest.
    """
    sk = comp.sketches.add(_offset_plane(comp, z_m))
    sk.name = name
    sk.isComputeDeferred = True        # large point sets are far faster this way

    col = adsk.core.ObjectCollection.create()
    for (x, y) in pts_m:
        col.add(_pt(x, y))
    sk.sketchCurves.sketchFittedSplines.add(col)

    # Close the blunt trailing edge with a line.
    sk.sketchCurves.sketchLines.addByTwoPoints(_pt(*pts_m[-1]), _pt(*pts_m[0]))

    sk.isComputeDeferred = False
    return sk.profiles.item(0) if sk.profiles.count > 0 else None


def _polygon_sketch(comp, z_m, pts_m, name):
    sk = comp.sketches.add(_offset_plane(comp, z_m))
    sk.name = name
    sk.isComputeDeferred = True
    lines = sk.sketchCurves.sketchLines
    n = len(pts_m)
    for i in range(n):
        lines.addByTwoPoints(_pt(*pts_m[i]), _pt(*pts_m[(i + 1) % n]))
    sk.isComputeDeferred = False
    return sk.profiles.item(0) if sk.profiles.count > 0 else None


def _loft(comp, profiles, name):
    if len(profiles) < 2:
        raise RuntimeError('%s: need at least 2 sections, got %d'
                           % (name, len(profiles)))
    lofts = comp.features.loftFeatures
    li = lofts.createInput(
        adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    for p in profiles:
        li.loftSections.add(p)
    li.isSolid = True
    feat = lofts.add(li)
    if feat.bodies.count > 0:
        feat.bodies.item(0).name = name
    return feat


def build_blade(parent, cfg, log):
    """Create the blade component: aeroshell, spar caps, shear webs."""
    occ = parent.occurrences.addNewComponent(adsk.core.Matrix3D.create())
    comp = occ.component
    comp.name = 'Blade'

    stations = span_stations(cfg)

    # ---- aeroshell, BOM 1100 ---------------------------------------------
    profiles = []
    skipped = []
    for i, rR in enumerate(stations):
        pts = station_points(rR, cfg)
        prof = _closed_profile_sketch(
            comp, blade_z_m(rR, cfg), pts, 'Station_%02d_r%.3f' % (i, rR))
        if prof is None:
            skipped.append(i)
        else:
            profiles.append(prof)

    if skipped:
        log.append('Aeroshell: %d station(s) produced no closed profile and '
                   'were skipped: %s' % (len(skipped), skipped))

    _loft(comp, profiles, 'Aeroshell')
    log.append('Aeroshell lofted through %d of %d stations.'
               % (len(profiles), len(stations)))

    # ---- internal structure, BOM 1110 / 1120 ------------------------------
    if cfg['build_structure']:
        r0, r1 = cfg['structure_root_frac'], cfg['structure_tip_frac']
        inner = [r for r in stations if r0 <= r <= r1]
        if len(inner) < 2:
            inner = [r0, r1]

        for upper in (True, False):
            nm = 'SparCap_%s' % ('Upper' if upper else 'Lower')
            profs = []
            for i, rR in enumerate(inner):
                p = _polygon_sketch(comp, blade_z_m(rR, cfg),
                                    spar_cap_rect(rR, cfg, upper),
                                    '%s_%02d' % (nm, i))
                if p:
                    profs.append(p)
            _loft(comp, profs, nm)
            log.append('%s lofted through %d sections.' % (nm, len(profs)))

        for fore in (True, False):
            nm = 'ShearWeb_%s' % ('Fore' if fore else 'Aft')
            profs = []
            for i, rR in enumerate(inner):
                p = _polygon_sketch(comp, blade_z_m(rR, cfg),
                                    shear_web_rect(rR, cfg, fore),
                                    '%s_%02d' % (nm, i))
                if p:
                    profs.append(p)
            _loft(comp, profs, nm)
            log.append('%s lofted through %d sections.' % (nm, len(profs)))

    return comp


def build_hub(parent, cfg, log):
    """Hub: revolved body with three blade flanges at 120 deg. BOM 1200."""
    occ = parent.occurrences.addNewComponent(adsk.core.Matrix3D.create())
    comp = occ.component
    comp.name = 'Hub'

    r = 0.5 * cfg['hub_envelope_dia_m'] * M2CM

    # Half-disc profile in XY, revolved about the Y axis -> sphere.
    sk = comp.sketches.add(comp.xYConstructionPlane)
    sk.name = 'HubProfile'
    p0 = adsk.core.Point3D.create(0.0, r, 0.0)
    p1 = adsk.core.Point3D.create(0.0, -r, 0.0)
    axis = sk.sketchCurves.sketchLines.addByTwoPoints(p0, p1)
    axis.isConstruction = True
    sk.sketchCurves.sketchArcs.addByThreePoints(
        p0, adsk.core.Point3D.create(r, 0.0, 0.0), p1)

    if sk.profiles.count == 0:
        raise RuntimeError('Hub: revolve profile did not close.')

    revs = comp.features.revolveFeatures
    ri = revs.createInput(
        sk.profiles.item(0), axis,
        adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    ri.setAngleExtent(False, adsk.core.ValueInput.createByReal(2.0 * math.pi))
    feat = revs.add(ri)
    if feat.bodies.count > 0:
        feat.bodies.item(0).name = 'HubCasting'

    # Three blade flanges, 120 deg apart about the rotor (Y) axis.
    fr = 0.5 * cfg['hub_flange_dia_m'] * M2CM
    fl = cfg['hub_flange_len_m'] * M2CM
    base = 0.5 * cfg['hub_envelope_dia_m'] * M2CM * 0.85

    for k in range(cfg['n_blades']):
        ang = 2.0 * math.pi * k / cfg['n_blades']
        pin = comp.constructionPlanes.createInput()
        pin.setByOffset(comp.xYConstructionPlane,
                        adsk.core.ValueInput.createByReal(base))
        pl = comp.constructionPlanes.add(pin)

        fsk = comp.sketches.add(pl)
        fsk.name = 'Flange_%d' % k
        fsk.sketchCurves.sketchCircles.addByCenterRadius(
            adsk.core.Point3D.create(0.0, 0.0, 0.0), fr)
        if fsk.profiles.count == 0:
            continue

        ext = comp.features.extrudeFeatures.addSimple(
            fsk.profiles.item(0),
            adsk.core.ValueInput.createByReal(fl),
            adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
        if ext.bodies.count > 0:
            b = ext.bodies.item(0)
            b.name = 'BladeFlange_%d' % k
            # Rotate this flange into position about the rotor axis.
            if abs(ang) > 1e-9:
                m = adsk.core.Matrix3D.create()
                m.setToRotation(ang, adsk.core.Vector3D.create(0, 1, 0),
                                adsk.core.Point3D.create(0, 0, 0))
                col = adsk.core.ObjectCollection.create()
                col.add(b)
                mi = comp.features.moveFeatures.createInput(col, m)
                comp.features.moveFeatures.add(mi)

    log.append('Hub built with %d blade flanges.' % cfg['n_blades'])
    return comp


def build_spinner(parent, cfg, log):
    """Spinner / nose cone: revolved ogive fairing. BOM 1400."""
    occ = parent.occurrences.addNewComponent(adsk.core.Matrix3D.create())
    comp = occ.component
    comp.name = 'Spinner'

    r = 0.5 * cfg['spinner_dia_m'] * M2CM
    L = cfg['spinner_len_m'] * M2CM

    sk = comp.sketches.add(comp.xYConstructionPlane)
    sk.name = 'SpinnerProfile'

    axis = sk.sketchCurves.sketchLines.addByTwoPoints(
        adsk.core.Point3D.create(0.0, -0.35 * L, 0.0),
        adsk.core.Point3D.create(0.0, L, 0.0))
    axis.isConstruction = True

    # Ogive: quarter-ellipse nose from tip to max radius.
    col = adsk.core.ObjectCollection.create()
    n = 24
    for i in range(n + 1):
        t = i / float(n)
        col.add(adsk.core.Point3D.create(r * math.sin(0.5 * math.pi * t),
                                         L * math.cos(0.5 * math.pi * t), 0.0))
    sk.sketchCurves.sketchFittedSplines.add(col)

    lines = sk.sketchCurves.sketchLines
    lines.addByTwoPoints(adsk.core.Point3D.create(r, 0.0, 0.0),
                         adsk.core.Point3D.create(r, -0.35 * L, 0.0))
    lines.addByTwoPoints(adsk.core.Point3D.create(r, -0.35 * L, 0.0),
                         adsk.core.Point3D.create(0.0, -0.35 * L, 0.0))
    lines.addByTwoPoints(adsk.core.Point3D.create(0.0, -0.35 * L, 0.0),
                         adsk.core.Point3D.create(0.0, L, 0.0))

    if sk.profiles.count == 0:
        raise RuntimeError('Spinner: revolve profile did not close.')

    revs = comp.features.revolveFeatures
    ri = revs.createInput(
        sk.profiles.item(0), axis,
        adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
    ri.setAngleExtent(False, adsk.core.ValueInput.createByReal(2.0 * math.pi))
    feat = revs.add(ri)
    if feat.bodies.count > 0:
        feat.bodies.item(0).name = 'SpinnerShell'

    log.append('Spinner built.')
    return comp


def build_root_bolts(parent, cfg, log):
    """Representative root bolt circle. BOM 1500.

    CONFIG uses a reduced bolt count on purpose -- the BOM specifies 80-120
    per blade, and modelling all of them triples rebuild time for a feature
    nobody inspects individually at assembly level. Raise bolt_count if you
    need the real pattern.
    """
    occ = parent.occurrences.addNewComponent(adsk.core.Matrix3D.create())
    comp = occ.component
    comp.name = 'RootBolts'

    bcr = 0.5 * cfg['bolt_circle_dia_m'] * M2CM
    br = 0.5 * cfg['bolt_dia_m'] * M2CM
    bl = cfg['bolt_len_m'] * M2CM
    z = cfg['hub_radius_m'] * M2CM

    pin = comp.constructionPlanes.createInput()
    pin.setByOffset(comp.xYConstructionPlane,
                    adsk.core.ValueInput.createByReal(z))
    pl = comp.constructionPlanes.add(pin)

    sk = comp.sketches.add(pl)
    sk.name = 'BoltCircle'
    sk.isComputeDeferred = True
    for k in range(cfg['bolt_count']):
        a = 2.0 * math.pi * k / cfg['bolt_count']
        sk.sketchCurves.sketchCircles.addByCenterRadius(
            adsk.core.Point3D.create(bcr * math.cos(a), bcr * math.sin(a), 0.0),
            br)
    sk.isComputeDeferred = False

    made = 0
    for i in range(sk.profiles.count):
        ext = comp.features.extrudeFeatures.addSimple(
            sk.profiles.item(i),
            adsk.core.ValueInput.createByReal(bl),
            adsk.fusion.FeatureOperations.NewBodyFeatureOperation)
        if ext.bodies.count > 0:
            ext.bodies.item(0).name = 'RootBolt_%02d' % i
            made += 1

    log.append('Root bolts: %d modelled (BOM specifies 80-120 -- reduced '
               'for rebuild time).' % made)
    return comp


def add_user_parameters(design, cfg, log):
    """Publish the non-lofted dimensions as Fusion user parameters.

    Only these are genuinely parametric after the script finishes. The blade
    loft is not -- see header note 2. Publishing the ones that ARE, and saying
    so, beats implying the whole model rebuilds from the Parameters dialog.
    """
    prm = design.userParameters
    wanted = [
        ('wt_hub_envelope_dia', cfg['hub_envelope_dia_m'], 'Hub envelope diameter, BOM 1200'),
        ('wt_hub_flange_dia',   cfg['hub_flange_dia_m'],   'Blade flange diameter, BOM 1200'),
        ('wt_spinner_dia',      cfg['spinner_dia_m'],      'Spinner diameter, BOM 1400'),
        ('wt_spinner_len',      cfg['spinner_len_m'],      'Spinner length, BOM 1400'),
        ('wt_bolt_circle_dia',  cfg['bolt_circle_dia_m'],  'Root bolt circle, BOM 1500'),
        ('wt_bolt_dia',         cfg['bolt_dia_m'],         'Root bolt diameter M36, BOM 1500'),
    ]
    added = 0
    for name, val_m, comment in wanted:
        if prm.itemByName(name) is not None:
            continue
        try:
            prm.add(name,
                    adsk.core.ValueInput.createByReal(val_m * M2CM),
                    'cm', comment)
            added += 1
        except Exception:
            pass
    log.append('User parameters published: %d' % added)


# =============================================================================
# ENTRY POINT
# =============================================================================

def run(context):
    ui = None
    log = []
    try:
        app = adsk.core.Application.get()
        ui = app.userInterface

        # A fresh document, so re-running never merges into existing geometry.
        doc = app.documents.add(
            adsk.core.DocumentTypes.FusionDesignDocumentType)
        design = adsk.fusion.Design.cast(app.activeProduct)
        design.designType = adsk.fusion.DesignTypes.ParametricDesignType
        root = design.rootComponent
        try:
            root.name = 'RotorAssembly'
        except Exception:
            pass

        cfg = CONFIG
        add_user_parameters(design, cfg, log)

        blade = build_blade(root, cfg, log)

        # Blades 2..n: same component, rotated about the rotor (Y) axis, with
        # precone applied as a tilt about the chordwise axis. Re-using the one
        # component rather than rebuilding means editing the blade updates all
        # three -- which is the point of an assembly.
        yaxis = adsk.core.Vector3D.create(0, 1, 0)
        xaxis = adsk.core.Vector3D.create(1, 0, 0)
        origin = adsk.core.Point3D.create(0, 0, 0)
        precone = math.radians(cfg['precone_deg'])

        cone = adsk.core.Matrix3D.create()
        cone.setToRotation(precone, xaxis, origin)
        root.occurrences.item(0).transform = cone

        for k in range(1, cfg['n_blades']):
            m = adsk.core.Matrix3D.create()
            m.setToRotation(2.0 * math.pi * k / cfg['n_blades'], yaxis, origin)
            m.transformBy(cone)
            root.occurrences.addExistingComponent(blade, m)
        log.append('%d blade occurrences placed, precone %.1f deg.'
                   % (cfg['n_blades'], cfg['precone_deg']))

        if cfg['build_hub']:
            build_hub(root, cfg, log)
        if cfg['build_spinner']:
            build_spinner(root, cfg, log)
        if cfg['build_root_bolts']:
            build_root_bolts(root, cfg, log)

        # Report planform so the numbers can be checked against the BOM
        # without measuring the model.
        log.append('')
        log.append('Planform check (r/R, chord m, twist deg, t/c, prebend m):')
        for rR in (0.0, 0.1, 0.22, 0.5, 0.75, 1.0):
            log.append('  %.2f   %6.3f   %5.2f   %5.3f   %5.3f'
                       % (rR, chord_at(rR, cfg), twist_at(rR, cfg),
                          thickness_at(rR, cfg), prebend_at(rR, cfg)))

        app.activeViewport.fit()
        ui.messageBox('Rotor assembly built.\n\n' + '\n'.join(log),
                      'WindTurbineBlade')

    except Exception:
        msg = 'WindTurbineBlade failed:\n\n%s' % traceback.format_exc()
        if log:
            msg += '\n\nCompleted before the failure:\n' + '\n'.join(log)
        if ui:
            ui.messageBox(msg, 'WindTurbineBlade')
        else:
            print(msg)
